Sys.setenv(R_BIOC_VERSION="3.11")
options(repos=c(CRAN="file:///data/blackswan/ripley/R"))
#options(BioC_mirror="http://bioconductor.statistik.tu-dortmund.de")
#options(BioC_mirror="http://mirrors.ebi.ac.uk/bioconductor/")
options(BioC_mirror="http://bioconductor.org")
utils::setRepositories(ind=2:4)
.libPaths("~/R/BioC-3.11")
