#! /bin/csh
~/R/packages/InUse.R ~/R/packages/tests || exit 1
cd ~/R
./update
cd ~/R/R-patched
make -j10
./bin/Rscript -e 'update.packages(.Library, ask = F)'
Rscript -e 'update.packages(.Library, ask = F, type = "source")'
cd R/packages
~/R/packages/revdeps1 ~/R/test-4.0 ~/R/packages/tests/revdeps.rds
env R_LIBS=~/R/test-4.0 Rscript unavailable.R tests
env DISPLAY=:5 NOAWT=1 RMPI_TYPE=OPENMPI RGL_USE_NULL=true R_LIBS=~/R/test-4.0 Rscript updates.R
~/R/packages/revdeps2 ~/R/test-4.0 ~/R/packages/tests/revdeps.rds
rm -f ~/R/packages/tests/revdeps.rds
cd tests
make unpack
./script
