#! /bin/csh
pushd ~/R/M1mac >& /dev/null
foreach f (*.{out,log}) 
\cp -p ~/R/packages/tests-devel/$f . >& /dev/null
end
popd >& /dev/null
rsync -av --delete \
--exclude=README.txt~ \
  ~/R/M1mac/ \
  gannet:/data/ftp/pub/bdr/M1mac
